### ISSUE TITLE
想问一下可靠性如何？作者有把此工具用在线上项目吗？

### ISSUE THREAD

**Issue by bighw** [timandy/routine#10]
想问一下可靠性如何？作者有把此工具用在线上项目吗？go1.18.1可以使用吗？

**Comment by timandy** [comment]
@bighw 你好：
- 我们现在生产环境用的 go1.17，未出现任何性能和可靠性问题。用户量：日活 200 左右，注册用户 1w。
- go1.18 建议先等等，近期刚修复了个 1.18 关联的 bug，等发布后可以在小范围内尝试下。生产环境使用 go1.18 还是要谨慎。

**Comment by timandy** [comment]
@bighw 我们产品目前已升级到go1.18，坐标科大讯飞

**Comment by ezhishui** [comment]
> @bighw 我们产品目前已升级到go1.18，坐标科大讯飞

牛逼的教育大佬，我也是讯飞的哈哈  整体还稳定不？遇到本公司开源的有点畏缩了哈
