### ISSUE TITLE
[Question] can I directly modify the golang runtime?

### ISSUE THREAD

**Issue by oreak** [timandy/routine#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Excuse me, can I directly modify the golang runtime? 
Because this information is available in the runtime, such as goid or more information about GMP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@oreak  It depends. Unless you know the impact of modifying the runtime.
