### ISSUE TITLE
threadlocalmap用切片表示不能复用

### ISSUE THREAD

**Issue by fengyeall111** [timandy/routine#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

threadlocalmap不用id池吗，这样remove以后id一直递增了

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fengyeall111** [comment]
采用runtime.setFinilizer gc不会问题吗，协程栈扩容，还有runtime.setGoroutinueLables方法都会改变g.lables的地址。都会触发回收函数。真正需要回收的时候时协程退出的时候，需要hack的是goexit这个方法啊，不是setFinilizer这个方法

**Comment by timandy** [comment]
@fengyeall111 Please try to communicate in English.

> threadlocalmap不用id池吗，这样remove以后id一直递增了


首先要确保你的使用方式正确，`ThreadLocal` 变量需要定义为全局的。
通常在 App 的生命周期中，`ThreadLocal` 变量的数量不会太多。
`ThreadLocalMap` 的 `Key` 存储的是 `ThreadLocal` 的 `id`，该值在 `ThreadLocal` 初始化后不会改变，跟 `Remove()` 函数没有任何关联关系。参考：[https://zhuanlan.zhihu.com/p/462517486](https://zhuanlan.zhihu.com/p/462517486)

---

First, make sure you use it correctly. `ThreadLocal` variables need to be defined as global.

Usually, the number of `ThreadLocal` variables is not too large in the life cycle of an app.

The `Key` of `ThreadLocalMap` stores the `id` of `ThreadLocal`. This value will never be changed after `ThreadLocal` initialized so it has no association with the `Remove()` function. refer: [https://zhuanlan.zhihu.com/p/462517486](https://zhuanlan.zhihu.com/p/462517486)

**Comment by timandy** [comment]
> 采用runtime.setFinilizer gc不会问题吗，协程栈扩容，还有runtime.setGoroutinueLables方法都会改变g.lables的地址。都会触发回收函数。真正需要回收的时候时协程退出的时候，需要hack的是goexit这个方法啊，不是setFinilizer这个方法

`g.labels` 存储的是 `map[string]string` 的指针，跟协程栈是否扩容没有关系，无论怎么扩容 `g` 的堆栈 `g.labels` 的值不会受影响。

---

`g.labels` stores the pointer of `map[string]string`, and it has no-relation with whether the coroutine stack expands  or not. No matter how you expand the stack of `g` the value of `g.labels` will not be effected.

**Comment by timandy** [comment]
The issue was closed because there was no response for a long time.
If have other questions, you can reopen a new issue.
