### ISSUE TITLE
[build err] on go1.20

### ISSUE THREAD

**Issue by Dianwoung** [timandy/routine#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

go1.20版本编译异常：github.com/timandy/routine/g.getg0: relocation target type.runtime.g not defined

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@Dianwoung The golang linker has broken changed in version 1.20. Do you have any suggestions?

**Comment by timandy** [comment]
It’s in the go1.20 release notes: https://go.dev/doc/go1.20#linker.

**Comment by timandy** [comment]
Now the latest version of `routine` supports `go1.20`.
