### ISSUE TITLE
How to use the api ?

### ISSUE THREAD

**Issue by rdluffy** [timandy/routine#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Do we need to call the remove function on the thread local ?

I dont want to loose created variable in memory .

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
> Do we need to call the remove function on the thread local ?

The value which you set to threadLocal will be alive until the coroutine is dead, you can call `Get` method to get the value again.

If you want to remove the value, call `Remove` method.

When the worker coroutine dead, all the values bind to the coroutine will be removed automaticly, call `Remove` is not necessary.

**Comment by timandy** [comment]
No response for a long time, I will close this issue.
