### ISSUE TITLE
[Question] How does routine use g.labels to store data?

### ISSUE THREAD

**Issue by kong123456** [timandy/routine#28]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Question

thread 结构体的数据存在 g.labels 里
1. golang 的设计中，哪些golang自带的基础组件会占用到 g.labels 成员？
2. 怎么检测出 g.labels 成员被哪个模块占用？

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@kong123456 You are welcome to ask questions. Please use English for other personnel to review.

`pprof` used `g.labels` to store data, see this [issue](https://github.com/timandy/routine/issues/4#issuecomment-1079641465).

`routine` use struct layout to store data without intruding into the content of the `map[string]string` which  pointed by `g. labels`.

**Comment by timandy** [comment]
No response for a long time, I will close this issue.
