### ISSUE TITLE
为什么只有创建，而没有Get方法？

### ISSUE THREAD

**Issue by liangmanlin** [timandy/routine#3]

**Comment by timandy** [comment]
@liangmanlin 提供 Get,Set,Remove 方法的, 看下例子 https://github.com/timandy/routine#use-threadlocal

**Comment by liangmanlin** [comment]
我可能没有表达清楚，我的意思是，为什么没有`routine.GetLocal()`这样的方法

**Comment by timandy** [comment]
@liangmanlin 没有明白你的意思, 想通过 `GetLocal()` 实现什么样的功能?

**Comment by liangmanlin** [comment]
获取`routine.NewThreadLocal()`创建的对象

**Comment by timandy** [comment]
使用赋值即可获取创建的对象，var `tls` = routine.NewThreadLocal()。**tls** 就是创建的的对象。
写入数据的时候使用 tls.Set(value)
在其他函数读取数据的时候调用 tls.Get()，注意进行类型断言。
用完后使用 tls.Remove() 删除数据。

**Comment by liangmanlin** [comment]
如果要不停持有这个变量，那么这个库有什么作用？明显和线程专用变量的特性相违背

**Comment by timandy** [comment]
@liangmanlin  你可以将 `tls` 定义成全局变量。

**Comment by liangmanlin** [comment]
我之前没看全，现在知道了，但是这个用法有误导成分，go有包的概念，应该直接封装成rutine.Set(),rutine.Get() 比较方便

顺便一提，有没有支持泛型的打算

**Comment by timandy** [comment]
@liangmanlin go 1.18 的泛型不支持方法泛型，只支持函数泛型，所以没法支持的。

**Comment by liangmanlin** [comment]
我的意思就是改成纯方法

**Comment by liangmanlin** [comment]
> 这样封装不支持定义多个 ThreadLocal 变量，通常应用中不会只定义一个 ThreadLocal 变量。

我觉得是没必要的，如果你想要多个，大可以使结构体实现，也不会浪费多少性能

**Comment by timandy** [comment]
你的这些需求可以自己 fork 仓库实现。没有其他问题就关闭 issue 了。
