### ISSUE TITLE
[Question] invalid operation: cannot index routine.NewThreadLocal (value of type func() routine.ThreadLocal)

### ISSUE THREAD

**Issue by Castlebin** [timandy/routine#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

The example "Use ThreadLocal" does not work, it reports "invalid operation: cannot index routine.NewThreadLocal (value of type func() routine.ThreadLocal)", "invalid operation: cannot index routine.NewInheritableThreadLocal (value of type func() routine.ThreadLocal)
"

golang version 1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@Castlebin You can use v1.1.3 now. Please try again

**Comment by Castlebin** [comment]
> @Castlebin You can use v1.1.3 now. Please try again

Thanks!
