### ISSUE TITLE
如何验证thread是否被GC回收？占用的内存是否被释放？

### ISSUE THREAD

**Issue by YLLL-ux** [timandy/routine#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

```go
var (
	threadLocal1 = routine.NewThreadLocal[string]()
)

func main() {
	var m1 runtime.MemStats
	runtime.ReadMemStats(&m1)
	fmt.Printf("1 - %d Kb\n", m1.Alloc/1024)
        for i := 0; i < 1000; i++ {
          go func(){
             threadLocal1.Set("bigFile")
             time.Sleep(time.Second)

             threadLocal1.Get()
	     time.Sleep(time.Second)
	     
             var sub runtime.MemStats
	     runtime.ReadMemStats(&sub)
	     fmt.Printf("sub - %d Kb\n", sub.Alloc/1024)
           }
        }
        
        time.Sleep(time.Second * 5)

	var m2 runtime.MemStats
	runtime.ReadMemStats(&m2)
	fmt.Printf("2 - %d Kb\n", m2.Alloc/1024)
}
``` 

输出打印的内容使用量并没有下来。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YLLL-ux** [comment]
补充：在go协程中使用threadLocal1.Get()
			time.Sleep(time.Second * 8)

**Comment by timandy** [comment]
@YLLL-ux Golang's gc is not executed in real time. If you want to test whether it can be recycled, you need to manually call the gc method to start gc immediately.

**Comment by YLLL-ux** [comment]
请问您是有定期检测thread状态吗？

**Comment by timandy** [comment]
> 经过十多次测试后，发现每次Alloc归零的时间大约一致，这说明是进行了内存回收的。但是，我在您的源码中，没有找到具体回收的地方，请问源码中是在哪里回收的呢？？

Golang will automatically GC at the appropriate time during runtime.


> 请问是currentThread中的这段code的吗？ 

No, the purpose of this line is to reset the magic code.

> 请问您是有定期检测thread状态吗？
No need to check the status of `thread`.

**Comment by YLLL-ux** [comment]
@timandy thanks
