### ISSUE TITLE
When will version 1.22.5 be supported?

### ISSUE THREAD

**Issue by lp2jx0309** [timandy/routine#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

When will version 1.22.5 be supported?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonMing** [comment]
what's wrong with 1.22.5?

`//go:linkname` will be disabled in 1.23, it should be still available in 1.22.

**Comment by timandy** [comment]
@lp2jx0309 The latest version work fine with go1.22.

**Comment by manchurio** [comment]
> > what's wrong with 1.22.5?
> > `//go:linkname` will be disabled in 1.23([golang/go#67401](https://github.com/golang/go/issues/67401)), it should be still available in 1.22.
> 
> @JasonMing The break change only effected some testcases. I will release a new version after go1.23 released.

Today, Go has already released version 1.23.0, but this library is not compatible. When will the next version be released? I've tested it myself, and I just need to remove the '//go:linkname' from the [g0 struct](https://github.com/timandy/routine/blob/5dad6edb11ec2e7defb6c05216fc195cb3026d6e/g/g.go#L13), and everything works fine.

**Comment by timandy** [comment]
@manchurio The new version is coming these days.

**Comment by timandy** [comment]
Now go1.23 is supported. See the latest [release](https://github.com/timandy/routine/releases/latest).
