### ISSUE TITLE
代码段求解

### ISSUE THREAD

**Issue by liangmanlin** [timandy/routine#7]
https://github.com/timandy/routine/blob/118c0057402fdd7a0339e426798ba468a2e1aeea/thread.go#L65-L69

这一段代码的作用是什么，不太理解，希望可以解答一下

**Comment by timandy** [comment]
@liangmanlin 
**复现方法：**
去掉这段代码，运行 `TestPProf` 单元测试，如果无法复现，可以修改里面的并行度常量或多运行几次。

**详解：**
- 如果在设置 `threadLocal` 之前通过 `pprof.Do()` 函数对 `g.labels` 进行赋值，那么 `g.lables` 的 `unsafe.Pointer` 实际指向的是一个 `map[string]string`。
- 当运行到此的时候需要将 `g.labels` 转换成 `*thread`。需要注意的是这时这个 thread 是跨越多个对象的，如果在 race 模式下运行会产生 fault error（在 Golang中 fault error 是无法被 recover 捕获的），`go:nocheckptr` 可以在 `race` 模式下跳过检查指针是否跨越多个对象。
- 上一步转换成功的 `*thread` 指针实际上是跨越了多个对象的。其 `labels` 字段可以正常读取为 `map[string]string`，但是读取后边的其他字段就不一定能成功了（注意是不一定，可能成功但是 `magic` 是个其他的数字，也可能引发无效内存的 fault error）。
- 恰好这种读取未知内存的 fault error 引发之前会判断 `g.paniconfault` 字段（注意不是所有的 fault error 引发之前都会判断该值）。如果该字段为 true，则会产生一个 `panic` 而非 `fault error`，这样就可以使用 `recover` 捕获了。
- 捕获以后返回的 `magic` 值为 `0`，这样后续的逻辑就认为 这个` g.labels` 存储的是 `map[string]string`，而非需要的 `*thread`，从而正确的识别 `unsafe.Pointer` 的类型。

**性能影响：**
只有在修改了 `g.labels` 的协程上使用 `ThreadLocal`，因为 `panic` 和 `recover` 产生性能波动，其他协程上并无大碍。

**Comment by liangmanlin** [comment]
感谢答疑

**Comment by liangmanlin** [comment]
https://github.com/timandy/routine/blob/118c0057402fdd7a0339e426798ba468a2e1aeea/thread_test.go#L38

100个线程跑 TestPProf

实际这一行并不能通过，没有注释上面提及的疑惑代码

**Comment by timandy** [comment]
> 100个线程跑 TestPProf

@liangmanlin 你是使用 `go1.18-amd64` 测试的吧，这个问题我在另一个 issue 已经说明过了。

> 由于 go1.18-amd64 可能对 map 对象进行缓存，所以测试用例 TestPProf 存在一定失败的几率。
只要同一协程内 Set 后不进行额外的 labels 写入就不会出现问题，并在超出业务范围后及时 Remove。

**Comment by liangmanlin** [comment]
```golang
func TestPProf(t *testing.T) {
	const concurrency = 100
	const loopTimes = 10000
	tls := NewThreadLocal()
	tls.Set("你好")
	wg := &sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		tmp := i
		go func() {
			for j := 0; j < loopTimes; j++ {
				time.Sleep(10 * time.Millisecond)
				tls.Set(tmp)
				assert.Equal(t, tmp, tls.Get())
				pprof.Do(context.Background(), pprof.Labels("key", "value"), func(ctx context.Context) {
					tls.Set("hi")
					label, find := pprof.Label(ctx, "key")
					assert.True(t, find)
					assert.Equal(t, "value", label)
					//
					//assert.Nil(t, currentThread(false))
					//assert.Nil(t, tls.Get())
					//tls.Set("hi")
					assert.Equal(t, "hi", tls.Get())
					//
					label2, find2 := pprof.Label(ctx, "key")
					assert.True(t, find2)
					assert.Equal(t, "value", label2)
				})
				assert.Nil(t, tls.Get())
			}
			wg.Done()
		}()
	}
	assert.Nil(t, pprof.StartCPUProfile(&bytes.Buffer{}))
	wg.Wait()
	pprof.StopCPUProfile()
	assert.Equal(t, "你好", tls.Get())
}
```

使用上述测试代码，发现偶发如下报错

```bash
[root@ routine]# go test -run TestPProf
unexpected fault address 0x5f87cb
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5f87cb pc=0x598424]

goroutine 27 [running]:
runtime.throw({0x5f8c17?, 0xc00017f828?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000328d58 sp=0xc000328d28 pc=0x436dd1
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc000328da8 sp=0xc000328d58 pc=0x44cdc5
github.com/timandy/routine.(*threadLocalMap).set(...)
        /mnt/hgfs/go/routine/thread_local_map.go:24
github.com/timandy/routine.(*threadLocal).Set(0xc00005d400, {0x5bf720?, 0x6400b0})
        /mnt/hgfs/go/routine/thread_local.go:36 +0x64 fp=0xc000328de0 sp=0xc000328da8 pc=0x598424
github.com/timandy/routine.TestPProf.func1.1({0x641c40, 0xc000351ce0})
        /mnt/hgfs/go/routine/thread_test.go:34 +0x69 fp=0xc000328e70 sp=0xc000328de0 pc=0x5a98e9
runtime/pprof.Do({0x641bd0?, 0xc0000160c0?}, {{0xc00032ea40?, 0x742a98?, 0x5bee20?}}, 0xc000328fb0)
        /usr/local/go/src/runtime/pprof/runtime.go:40 +0xa3 fp=0xc000328ee0 sp=0xc000328e70 pc=0x5092e3
github.com/timandy/routine.TestPProf.func1()
        /mnt/hgfs/go/routine/thread_test.go:33 +0xe7 fp=0xc000328fe0 sp=0xc000328ee0 pc=0x5a95a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000328fe8 sp=0xc000328fe0 pc=0x4681e1
created by github.com/timandy/routine.TestPProf
        /mnt/hgfs/go/routine/thread_test.go:28 +0x8e
```

在windows平台不会发生

go1.18.1

目前可以猜测的是，`thread`经过gc后，是没有重置数据的

我提了一个pr，你可以看看这样处理是否可以解决

**Comment by liangmanlin** [comment]
> @liangmanlin **复现方法：** 去掉这段代码，运行 `TestPProf` 单元测试，如果无法复现，可以修改里面的并行度常量或多运行几次。
> 
> **详解：**
> 
> * 如果在设置 `threadLocal` 之前通过 `pprof.Do()` 函数对 `g.labels` 进行赋值，那么 `g.lables` 的 `unsafe.Pointer` 实际指向的是一个 `map[string]string`。
> * 当运行到此的时候需要将 `g.labels` 转换成 `*thread`。需要注意的是这时这个 thread 是跨越多个对象的，如果在 race 模式下运行会产生 fault error（在 Golang中 fault error 是无法被 recover 捕获的），`go:nocheckptr` 可以在 `race` 模式下跳过检查指针是否跨越多个对象。
> * 上一步转换成功的 `*thread` 指针实际上是跨越了多个对象的。其 `labels` 字段可以正常读取为 `map[string]string`，但是读取后边的其他字段就不一定能成功了（注意是不一定，可能成功但是 `magic` 是个其他的数字，也可能引发无效内存的 fault error）。
> * 恰好这种读取未知内存的 fault error 引发之前会判断 `g.paniconfault` 字段（注意不是所有的 fault error 引发之前都会判断该值）。如果该字段为 true，则会产生一个 `panic` 而非 `fault error`，这样就可以使用 `recover` 捕获了。
> * 捕获以后返回的 `magic` 值为 `0`，这样后续的逻辑就认为 这个` g.labels` 存储的是 `*map[string]string`，而非需要的 `*thread`，从而正确的识别 `unsafe.Pointer` 的类型。
> 
> **性能影响：** 只有在修改了 `g.labels` 的协程上使用 `ThreadLocal`，因为 `panic` 和 `recover` 产生性能波动，其他协程上并无大碍。

经过多次测试，是否注释掉代码都不会触发`fault ` ，目前猜测是内存充足的时候，这种访问合法？

**Comment by timandy** [comment]
@liangmanlin 这个问题请重新开一个 issue 吧

**Comment by liangmanlin** [comment]
> @liangmanlin 这个问题请重新开一个 issue 吧

已提

**Comment by timandy** [comment]
> 经过多次测试，是否注释掉代码都不会触发`fault ` ，目前猜测是内存充足的时候，这种访问合法？

去掉 Sleep 函数，就很容易复现了。

这样访问时没有问题的，因为这个接口go 也是公开的，参考 `debug.SetPanicOnFault()`，我这么做的目的是减少一次 `g` 的获取。

**Comment by timandy** [comment]
删除了与该问题不相关的讨论。如果该话题没有疑问就关闭了。

**Comment by liangmanlin** [comment]
> 删除了与该问题不相关的讨论。如果该话题没有疑问就关闭了。

其他疑问另开吧
